In [1]:
import os
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

In [2]:
environment_name = 'CartPole-v1'
env = gym.make(environment_name)

In [3]:
environment_name

'CartPole-v1'

In [4]:
episodes = 5
for episode in range(1, episodes + 1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info, _ = env.step(action)
        score += reward
    print('Episode:{} Score:{}'.format(episode, score))

env.close()


Episode:1 Score:22.0
Episode:2 Score:15.0
Episode:3 Score:27.0
Episode:4 Score:23.0
Episode:5 Score:14.0


D:\Software\Anaconda\pkg\envs\VisualIntervention\Lib\site-packages\gym\envs\classic_control\cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(
D:\Software\Anaconda\pkg\envs\VisualIntervention\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [5]:
env.reset()

(array([ 0.01750497,  0.02629052, -0.03772727, -0.01677893], dtype=float32),
 {})

In [6]:
episodes = 5
for episode in range(1, episodes+1):
    print(episode)

1
2
3
4
5


In [7]:
env.reset()

(array([-0.0282611 , -0.03701731,  0.01570831, -0.04062297], dtype=float32),
 {})

In [8]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [9]:
env.step(1)

(array([-0.02900145,  0.15787591,  0.01489586, -0.32830867], dtype=float32),
 1.0,
 False,
 False,
 {})

In [10]:
env.observation_space.sample()

array([-2.7848816e+00,  1.5430731e+38, -3.6797978e-02,  1.4462641e+38],
      dtype=float32)

In [11]:
env.action_space.sample()

0

In [12]:
env.action_space

Discrete(2)

In [13]:
env.observation_space.sample()

array([ 3.5666826e+00, -1.5152727e+38, -1.0846296e-01,  5.2979540e+37],
      dtype=float32)

In [14]:
env.action_space.sample()

0

In [15]:
 log_path = os.path.join('Training', 'Logs')

In [16]:
 log_path

'Training\\Logs'

In [17]:
 env = gym.make(environment_name)
 env = DummyVecEnv([lambda: env])
 model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

D:\Software\Anaconda\pkg\envs\VisualIntervention\Lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


Using cuda device


D:\Software\Anaconda\pkg\envs\VisualIntervention\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(


In [18]:
PPO??

In [19]:
model.learn(total_timesteps=20000)

Logging to Training\Logs\PPO_5


D:\Software\Anaconda\pkg\envs\VisualIntervention\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


-----------------------------
| time/              |      |
|    fps             | 599  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 488         |
|    iterations           | 2           |
|    time_elapsed         | 8           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.007993591 |
|    clip_fraction        | 0.0771      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.687      |
|    explained_variance   | 0.00264     |
|    learning_rate        | 0.0003      |
|    loss                 | 6.51        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0123     |
|    value_loss           | 51.5        |
-----------------------------------------
----------------------------------

In [20]:
PPO_Path = os.path.join('Training', 'Saved Models', 'PPO_Model_Cartpole')

In [21]:
model.save(PPO_Path)

In [22]:
del model

In [23]:
PPO_Path

'Training\\Saved Models\\PPO_Model_Cartpole'

In [24]:
model = PPO.load(PPO_Path, env = env)

In [25]:
model.learn(total_timesteps=1000)

Logging to Training\Logs\PPO_6
-----------------------------
| time/              |      |
|    fps             | 155  |
|    iterations      | 1    |
|    time_elapsed    | 13   |
|    total_timesteps | 2048 |
-----------------------------


In [26]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

D:\Software\Anaconda\pkg\envs\VisualIntervention\Lib\site-packages\stable_baselines3\common\evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
D:\Software\Anaconda\pkg\envs\VisualIntervention\Lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py:243: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


(500.0, 0.0)

In [27]:
env.close()

In [28]:
episodes = 5
for episode in range(1, episodes + 1):
    obs = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action, _ = model.predict(obs)
        obs, reward, done, info = env.step(action)
        score += reward
    print('Episode:{} Score:{}'.format(episode, score))

#env.close()

Episode:1 Score:[500.]
Episode:2 Score:[319.]
Episode:3 Score:[500.]
Episode:4 Score:[414.]
Episode:5 Score:[500.]


In [29]:
env.close()

In [30]:
obs = env.reset()

In [31]:
model.predict(obs)

(array([1], dtype=int64), None)

In [32]:
env.action_space.sample()

0

In [33]:
env.step(action)

(array([[ 3.4712858e-02,  1.9512530e-01,  2.3613403e-04, -3.3370662e-01]],
       dtype=float32),
 array([1.], dtype=float32),
 array([False]),
 [{'TimeLimit.truncated': False}])

In [34]:
training_log_path = os.path.join(log_path, "PPO_2")

In [35]:
training_log_path

'Training\\Logs\\PPO_2'

In [ ]:
!tensorboard --logdir={training_log_path}

In [79]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold, EvalCallback

In [82]:
save_path = os.path.join('Training', 'Saved Models')

In [83]:
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=200, verbose=1)
eval_callback = EvalCallback(env,
                             callback_on_new_best=stop_callback,
                             eval_freq=10000,
                             best_model_save_path=save_path,verbose=1)

In [84]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=training_log_path)

Using cuda device


In [86]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training\Logs\PPO_2\PPO_2
-----------------------------
| time/              |      |
|    fps             | 76   |
|    iterations      | 1    |
|    time_elapsed    | 26   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 96          |
|    iterations           | 2           |
|    time_elapsed         | 42          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008251371 |
|    clip_fraction        | 0.0866      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.631      |
|    explained_variance   | 0.236       |
|    learning_rate        | 0.0003      |
|    loss                 | 19.6        |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.019      |
|    value_loss           | 53.2        |
---------------------------------------

In [87]:
new_arch = [dict(pi=[128,128,128,128], vf=[128,128,128,128])]

In [89]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path, policy_kwargs={'net_arch': new_arch})


Using cuda device


D:\Software\Anaconda\pkg\envs\VisualIntervention\Lib\site-packages\stable_baselines3\common\policies.py:486: UserWarning: As shared layers in the mlp_extractor are removed since SB3 v1.8.0, you should now pass directly a dictionary and not a list (net_arch=dict(pi=..., vf=...) instead of net_arch=[dict(pi=..., vf=...)])
  warnings.warn(


In [90]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training\Logs\PPO_3
-----------------------------
| time/              |      |
|    fps             | 99   |
|    iterations      | 1    |
|    time_elapsed    | 20   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 114         |
|    iterations           | 2           |
|    time_elapsed         | 35          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.015257328 |
|    clip_fraction        | 0.222       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | -0.00573    |
|    learning_rate        | 0.0003      |
|    loss                 | 3.11        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.023      |
|    value_loss           | 19.7        |
-----------------------------------------
---

In [93]:
env.render()

In [91]:
from stable_baselines3 import DQN

In [ ]:
model = DQN('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

In [1]:
model.learn(total_timesteps=20000, callback=eval_callback)

NameError: name 'model' is not defined